### ISSUE TITLE
roll 0.5.5

### ISSUE THREAD

**Issue by fedy2** [dart-lang/core-elements#188]
Version 0.5.3 introduces core-resizable which lets us handle core-list re/sizing issues.
Version 0.5.4 revert a commit in 0.5.3.

**Comment by fedy2** [comment]
There is any plan on rolling 0.5.4?

**Comment by jakemac53** [comment]
We are focused on preparing for polymer 0.8 at this time.

I agree that core-resizable would be great to have,  but we have to evaluate the best way to make it work since we have ported core-list to dart. It probably means also porting core-resizable to a dart mixin, but we haven't had a chance to evaluate that yet.

**Comment by fedy2** [comment]
OK. Thank you for the information.
